export const FILTER_BY_DIET = "FILTER_BY_DIET";
export const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";
export const SORT_BY_ALPHABETICAL_ORDER = "SORT_BY_ALPHABETICAL_ORDER";
export const SORT_BY_HEALTH_SCORE = "SORT_BY_HEALTH_SCORE";
export const GET_RECIPES_DB = "GET_RECIPES_DB";
export const GET_RECIPES_API = "GET_RECIPES_API";
